PSP/Controllers/ParameterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PSP.Controllers
{
    [Authorize]
    public class ParameterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PSP/Controllers/Report/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using PSP.Models;
using Microsoft.AspNetCore.Http;

namespace PSP.Controllers.Reports
{
    [Authorize]
    public class ReportController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.User = HttpContext.Session.GetString("UserId");
            return View();
        }

        public IActionResult AuditTrail()
        {
            ViewBag.User = HttpContext.Session.GetString("UserId");
            return View();
        }

        public JsonResult AuditTrailReport()
        {
            return Json(new Models.AuditTrail().GetList());
        }

        public IActionResult DownloadViewPDF()
        {
            var model = new AuditTrailModel();
            return new ViewAsPdf("AuditTrail");

        }
    }
}

PSP/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PSP.Models;
using System;

namespace PSP.Controllers
{
    [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
    [Authorize]
    public class UsersController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.User = HttpContext.Session.GetString("UserId");
            return View();
        }

        public JsonResult GetUsersList()
        {
            return Json(new Models.Payroll_Users().GetList());
        }

        [HttpPost]
        public JsonResult InsertUser([FromBody] Payroll_Users_MODEL model)
        {
            Response response = new Response(); 
            using (Payroll_Users user = new Payroll_Users())
            {
                if (user.InsertUser(model) > 0)
                {
                    response.ResponseStat = 1;
                    response.Description = "User saved!";

                    using (Models.AuditTrail audit = new AuditTrail())
                    {
                        audit.Insert(new Models.AuditTrailModel()
                        {
                            Control_No = 2,
                            UserName = HttpContext.Session.GetString("UserId"),
                            Details = "Create User",
                            Date_Time = DateTime.Now
                        });
                    }
                    return Json(response);
                }
                else
                {
                    response.ResponseStat = 0;
                    response.Description = "User failed to save!";
                    return Json(response);
                }
            }
        }

        public JsonResult SearchUser(string UserName)
        {
            return Json(new Models.Payroll_Users().GetUser(UserName));
        }

        public JsonResult SearchEmployeeID(string sEmployeeID)
        {
            CTBC.Network.ActiveDirectory ad = new CTBC.Network.ActiveDirectory("LDAP://chinatrust.com.ph", "Z_ESSDEV", "Welcome1");
            var data = ad.GetUserDetailsSingle(sEmployeeID);
            return Json(data);
        }

        [HttpPost]
        public JsonResult ActivateUser([FromBody] Payroll_Users_MODEL model)
        {
            Response response = new Response();
            using (Payroll_Users user = new Payroll_Users())
            {
                if (user.ActivateUser(model.UserName) == 0)
                {
                    if(model.UserName == HttpContext.Session.GetString("UserId"))
                        response.ResponseStat = 2;
                    else
                        response.ResponseStat = 1;
                   
                    response.Description = "User Deactivated!";
                }
                else
                {
                    response.Description = "User Activated!";
                }
            }
            using (Models.AuditTrail audit = new AuditTrail())
            {
                audit.Insert(new Models.AuditTrailModel()
                {
                    Control_No = 4,
                    UserName = HttpContext.Session.GetString("UserId"),
                    Details = "Delete User",
                    Date_Time = DateTime.Now
                });
            }
            return Json(response);
        }

        [HttpPost]
        public JsonResult EditUser([FromBody] Payroll_Users_MODEL model)
        {
            Response response = new Response();
            using (Payroll_Users user = new Payroll_Users())
            {
                if (user.EditUser(model) > 0)
                {
                    if (model.UserName == HttpContext.Session.GetString("UserId"))
                        response.ResponseStat = 2;
                    else
                        response.ResponseStat = 1;

                    response.Description = "User updated!";
                }
            }
            using (Models.AuditTrail audit = new AuditTrail())
            {
                audit.Insert(new Models.AuditTrailModel()
                {
                    Control_No = 3,
                    UserName = HttpContext.Session.GetString("UserId"),
                    Details = "Edit User",
                    Date_Time = DateTime.Now
                });
            }
            return Json(response);
        }
    }
}

PSP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PSP</title>
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/bootstrap-table/bootstrap-table.css" rel="stylesheet" />
    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/jquery/jquery.min.js"></script>
    @*<script src="~/bootstrap/js/bootstrap.js"></script>*@
    <script src="~/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/bootstrap-table/bootstrap-table.js"></script>
    <script src="~/sweetalert/sweetalert.min.js"></script>
    <script src="~/sweetalert2/sweetalert2.all.js"></script>
    <script src="~/font-awesome/js/all.js"></script>

</head>
<body>
    <main>
        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0" style="background-color: lightgray">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-black text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Payroll Partner</span>
                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="sidemenu">
                            <li class="nav-item">
                                <a href="/" class="nav-link px-0 align-middle">
                                    <i class="fs-4 fa-solid fa-file"></i> <span class="ms-1 d-none d-sm-inline">File Conversion</span>
                                </a>
                                @*<ul class="collapse show nav flex-column ms-1" id="homemenu" data-bs-parent="#sidemenu">
                                    <li class="w-100">
                                        <a href="#" class="nav-link px-0"><i class="fa-solid fa-file-import"></i><span class="d-none d-sm-inline"  style="color: #084298;font-size: small"> Retrieve File</span></a>
                                    </li>
                                </ul>*@
                            </li>
                            <li>
                                <a href="#reportmenu" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                                    <i class="fs-4 fa-solid fa-book"></i> <span class="ms-1 d-none d-sm-inline">Report</span>
                                </a>
                                <ul class="collapse nav flex-column ms-1" id="reportmenu" data-bs-parent="#sidemenu">
                                    <li class="w-100">
                                        <a href="@Url.Action("AuditTrail", "Report")" class="nav-link px-0"><i class="fs-6 fa-solid fa-file-pen"></i><span class="d-none d-sm-inline" style="color: #084298;font-size: small"> Audit Trail</span></a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#adminmenu" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                                    <i class="fa-solid fa-users"></i> <span class="ms-1 d-none d-sm-inline">Admin</span>
                                </a>
                                <ul class="collapse nav flex-column ms-1" id="adminmenu" data-bs-parent="#sidemenu">
                                    <li class="w-100">
                                        <a href="@Url.Action("Index", "Users")" class="nav-link px-0"><i class="fs-6 fa-solid fa-users-gear"></i><span class="d-none d-sm-inline" style="color: #084298;font-size: small"> User Management</span></a>
                                    </li>
                                     <li class="w-100">
                                        <a href="@Url.Action("Index", "Parameter")" class="nav-link px-0"><i class="fs-6 fa-solid fa-users-gear"></i><span class="d-none d-sm-inline" style="color: #084298;font-size: small"> Parameter settings</span></a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <hr>
                        <div class="dropdown pb-4">
                            <a href="#" class="d-flex align-items-center text-black text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="~/images/default-user.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                                <span class="d-none d-sm-inline mx-1 text-black">Hi, @ViewBag.User!</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                                <li><a class="dropdown-item" href="@Url.Action("Logout", "Login")">Sign out</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                @RenderBody()
            </div>
        </div>
    </main>
    @*    <main>
    @RenderBody()
    </main>*@
    @*
    <footer class="border-top footer text-muted text-center">
    <div class="container">
    &copy; @DateTime.Now.Year - CTBC BANK (PHILIPPINES) CORP.
    </div>
    </footer>*@
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PSP/Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PSP - Login</title>
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/sweetalert/sweetalert.min.js"></script>
    <script src="~/sweetalert2/sweetalert2.all.js"></script>
    <script src="~/font-awesome/js/all.js"></script>
    <script src="~/aes-js/index.js"></script>
    @*<link href="~/css/Login.css" rel="stylesheet" />*@
</head>
<body class="text-center" style="background-color: #1987545c">
    @RenderBody()
</body>
</html>